name: Node Example
on:
  push:
    branches:
      - node
env:

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
      - name: use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: ls
        run: ls
      - name: run node script
        run: node index.js